// Generated by tools/generate.mjs (CLI). Encrypted blobs must not be hand-edited.
window.DINO_DATA = {
  "config": {
    "title": "DINOVERSE",
    "heroSub": "OUR APPS, ONE PLACE."
  },
  "apps": [
    {
      "id": "flowdesk",
      "name": "FlowDesk",
      "description": "",
      "version": "1.0.0",
      "platforms": [
        "win"
      ],
      "image": "image/flowdesk.png",
      "lock": "open",
      "files": [
        {
          "label": "Windows 설치 (.exe)",
          "url": "https://example.com/FlowDesk-Setup.exe",
          "size": "—"
        }
      ]
    },
    {
      "id": "brachy",
      "name": "Brachy",
      "description": "",
      "version": "1.0.0",
      "platforms": [
        "win"
      ],
      "lock": "own",
      "enc": {
        "v": 1,
        "iter": 250000,
        "salt": "4UrUWMODX0riOe0/imF2qw==",
        "iv": "UBX2gh12qmQbxtnE",
        "ct": "14t77pS4CsS2b5pCTzz67qmy2Sh2x80EBRA6GoyV7hsnppGBaLpOa8fHUAyroUEkQ9iNH5W61sgwUZjN0wacByrw79Ua6Yx8Rx559S6DNMt1QZ4TLcIlp68qYjh1t4xbhlq2ggaOGQla2oCiYR1dh9D4LgXHJwm/VySWd7eScQ5s1g=="
      }
    },
    {
      "id": "sowhat-dino",
      "name": "SoWhat-Dino",
      "description": "",
      "version": "0.1.0",
      "platforms": [
        "win"
      ],
      "image": "image/sowhat-dino.png",
      "lock": "open",
      "files": [
        {
          "label": "Windows 설치 (.msi)",
          "url": "https://example.com/SoWhat-Dino.msi",
          "size": "—"
        }
      ]
    }
  ]
};
