// CLI generator for data.js — mirrors assets/crypto.js so the browser can decrypt
// what this produces. Usage:  node tools/generate.mjs [config.json] [out.js]
//
// Config shape:
// {
//   "config": { "title": "...", "heroSub": "..." },
//   "pagePassword": "....",
//   "apps": [
//     { "id":"flowdesk", "name":"FlowDesk", "description":"", "version":"1.0.0",
//       "platforms":["win"], "password":"appCode", "publish":true,
//       "files":[ { "label":"Windows (.exe)", "url":"https://...", "size":"42 MB" } ],
//       "notes":"" }
//   ]
// }
// If an app's "password" is empty/omitted, its downloads are protected by the page
// code only (lock:"page"). Otherwise they need their own code (lock:"own").

import { readFileSync, writeFileSync } from 'node:fs';

const ITER = 250000;
const enc = new TextEncoder();
const b64 = (buf) => Buffer.from(buf).toString('base64');

async function deriveKey(password, salt) {
  const baseKey = await crypto.subtle.importKey('raw', enc.encode(password), 'PBKDF2', false, ['deriveKey']);
  return crypto.subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: ITER, hash: 'SHA-256' },
    baseKey,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt', 'decrypt']
  );
}

async function encryptJSON(obj, password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const key = await deriveKey(password, salt);
  const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, enc.encode(JSON.stringify(obj)));
  return { v: 1, iter: ITER, salt: b64(salt), iv: b64(iv), ct: b64(new Uint8Array(ct)) };
}

const cfgPath = process.argv[2] || 'tools/config.demo.json';
const outPath = process.argv[3] || 'data.js';
const cfg = JSON.parse(readFileSync(cfgPath, 'utf8'));

if (!cfg.pagePassword) throw new Error('pagePassword is required in config');

const published = (cfg.apps || []).filter((a) => a.publish !== false);

const listItems = published.map((a) => ({
  id: a.id,
  name: a.name || a.id,
  description: a.description || '',
  version: a.version || '',
  platforms: a.platforms || [],
  lock: a.password && a.password.length ? 'own' : 'page',
}));

const data = {
  config: cfg.config || {},
  list: await encryptJSON(listItems, cfg.pagePassword),
  downloads: {},
};

for (const a of published) {
  const pw = a.password && a.password.length ? a.password : cfg.pagePassword;
  data.downloads[a.id] = await encryptJSON({ files: a.files || [], notes: a.notes || '' }, pw);
}

const banner = '// AUTO-GENERATED by tools/generate.mjs or admin.html. Do not edit by hand.\n';
writeFileSync(outPath, banner + 'window.DINO_DATA = ' + JSON.stringify(data, null, 2) + ';\n');
console.log(`wrote ${outPath} — ${published.length} app(s) published`);
