// CLI generator for data.js — mirrors assets/crypto.js so the browser can decrypt.
// Usage:  node tools/generate.mjs [config.json] [out.js]
//
// Per-app codes only (no page code). App list/metadata is public; each app's
// files are either open (plaintext) or locked (encrypted with the app's code).
//
// Config shape:
// {
//   "config": { "title": "...", "heroSub": "..." },
//   "apps": [
//     { "id":"flowdesk", "name":"FlowDesk", "description":"", "version":"1.0.0",
//       "platforms":["win"], "password":"", "publish":true,
//       "files":[ { "label":"Windows (.exe)", "url":"https://...", "size":"42 MB" } ],
//       "notes":"" }
//   ]
// }
// password empty/omitted -> lock:"open" (files plaintext). Otherwise lock:"own"
// (files encrypted with that password).

import { readFileSync, writeFileSync } from 'node:fs';

const ITER = 250000;
const enc = new TextEncoder();
const b64 = (buf) => Buffer.from(buf).toString('base64');

async function deriveKey(password, salt) {
  const baseKey = await crypto.subtle.importKey('raw', enc.encode(password), 'PBKDF2', false, ['deriveKey']);
  return crypto.subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: ITER, hash: 'SHA-256' },
    baseKey, { name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']);
}

async function encryptJSON(obj, password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const key = await deriveKey(password, salt);
  const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, enc.encode(JSON.stringify(obj)));
  return { v: 1, iter: ITER, salt: b64(salt), iv: b64(iv), ct: b64(new Uint8Array(ct)) };
}

const cfgPath = process.argv[2] || 'tools/config.local.json';
const outPath = process.argv[3] || 'data.js';
const cfg = JSON.parse(readFileSync(cfgPath, 'utf8'));

const published = (cfg.apps || []).filter((a) => a.publish !== false);

const apps = [];
for (const a of published) {
  const base = {
    id: a.id, name: a.name || a.id, description: a.description || '',
    version: a.version || '', platforms: a.platforms || [],
  };
  if (a.image) base.image = a.image; // public sticker art (decoration only)
  if (a.password && a.password.length) {
    apps.push({ ...base, lock: 'own', enc: await encryptJSON({ files: a.files || [], notes: a.notes || '' }, a.password) });
  } else {
    apps.push({ ...base, lock: 'open', files: a.files || [] });
  }
}

const data = { config: cfg.config || {}, apps };
const banner = '// Generated by tools/generate.mjs (CLI). Encrypted blobs must not be hand-edited.\n';
writeFileSync(outPath, banner + 'window.DINO_DATA = ' + JSON.stringify(data, null, 2) + ';\n');
console.log(`wrote ${outPath} — ${apps.length} app(s) (${apps.filter(a => a.lock === 'own').length} locked)`);
